# This file describes the network interfaces available on your system

# For more information, see netplan(5).

network:
  version: 2
  renderer: networkd
  ethernets:
          ens18:
                  dhcp4: no
                  dhcp6: no
                  addresses: [51.79.62.9/32]
                  gateway4: 66.70.180.254
                  nameservers:
                          addresses: [1.1.1.1,1.0.0.1]
                  routes:
                  - to: 66.70.180.254/32
                    via: 0.0.0.0
                    scope: link
